### ISSUE TITLE
Test discovery in `class`es fails unless all fields contain doctest

### ISSUE THREAD

**Issue by Iron-E** [ssssota/doc-vitest#58]
Hello! Thank you for this plugin. I sorely missed doctests, coming from Rust.

Here is a minimum example of the issue:

```typescript
class Foo {
	public constructor() { }

	/** some note about this property */ // ← this causes the test discovery to fail
	private readonly bar: number = 3;

	/**
	 * @import.meta.vitest
	 * ```ts
	 * assert(false);
	 * ```
	 */
	public readonly baz = (): void => { }
}
```

**Comment by ssssota** [comment]
Thank you for using!
I have fixed this issue.
Please check [v0.1.3](https://github.com/ssssota/doc-vitest/releases/tag/vite-plugin-doctest%400.1.3)!
