### ISSUE TITLE
Add example for Nuxt

### ISSUE THREAD

**Issue by Rednas83** [ssssota/doc-vitest#84]
I would like to try it with nuxt.

Can the setup be done with **nuxt.config.ts**?

Tried:
```
import { doctest } from 'vite-plugin-doctest';
export default defineNuxtConfig({
  plugins: [doctest({ /* options */ })],
  test: {
    includeSource: [
      './src/**/*.[jt]s?(x)',
      './**/*.md', // You can disable markdown test by removing this line
    ],
  },
})
```

But it returns an error
![image](https://github.com/user-attachments/assets/1f04711c-f012-44ab-8e0b-9d47249840a3)

**Comment by ssssota** [comment]
If you want to use vitest at Nuxt project, you should put a `vitest.config.ts` ([official document](https://nuxt.com/docs/getting-started/configuration#:~:text=More%20Info-,vitest,-vitest.config.ts)).
And, you can configuration testing at `vitest.config.ts`.

Here is the example!
https://stackblitz.com/edit/nuxt-doctest?file=vitest.config.ts,functions%2Fsome-function.ts

fyi: vite-plugin-doctest **cannot** test comment in `.vue` files.
